{
 "title": "Overview - Sonicwall (Caio Btu)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview - Caio Btu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "options": {
    "content": "<center><img src=\"https://d3ik27cqx8s5ub.cloudfront.net/bt/img/Logo.svg\" width=\"500px\"/></center>   "
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 9, "y": 1 },
   "options": {
    "content": "<center><img src=\"https://i.ibb.co/b7jGfn6/Sonic-Wall-NSA-3700.png\" width=\"700px\"/></center>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:92",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Primary" ],
       "text": "setAlias(Primary)"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Primario" },
     "item": { "filter": "UpTime" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:113",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " Secondary" ],
       "text": "setAlias( Secondary)"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Secundario" },
     "item": { "filter": "UpTime" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informations",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Sonicwall Model" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Firmware Version" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Sonicwall Serial Number" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Memory User" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Memory User" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Current Connections" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Current Connections" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Licenses",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "source": "url",
     "type": "json",
     "url": "https://172.16.1.150:4443/api/sonicos/reporting/license/security-services",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "DLPI-SSL - States Connections",
   "type": "gauge",
   "description": "Máx.: 750000",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "DPI SSL Current" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:240",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Data Plane" ],
       "text": "setAlias(Data Plane)"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": { "filter": "Current CPU Util DataPlane" },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:261",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Management Plane" ],
       "text": "setAlias(Management Plane)"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Current CPU Util .Management Plane"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LAN Networks Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9572",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0 (LAN)" ],
       "text": "setAlias(In X0 (LAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0 (LAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9593",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X4 (LB)" ],
       "text": "setAlias(In X4 (LB))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X4 (LB)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9614",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X22 (HA-Link)" ],
       "text": "setAlias(In X22 (HA-Link))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X22 (HA-Link)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9635",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X23 (HA Data Link)" ],
       "text": "setAlias(In X23 (HA Data Link))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X23 (HA Data Link)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9656",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0 (LAN)" ],
       "text": "setAlias(Out X0 (LAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0 (LAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9677",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X4 (LB)" ],
       "text": "setAlias(Out X4 (LB))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X4 (LB)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9698",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X22 (HA-Link)" ],
       "text": "setAlias(Out X22 (HA-Link))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X22 (HA-Link)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:9719",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X23 (HA Data Link)" ],
       "text": "setAlias(Out X23 (HA Data Link))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X23 (HA Data Link)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "WAN Networks Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:10214",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X1 (WAN)" ],
       "text": "setAlias(In X1 (WAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X1 (WAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:10235",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X2 (WAN)" ],
       "text": "setAlias(In X2 (WAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X2 (WAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:10256",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X3 (WAN)" ],
       "text": "setAlias(In X3 (WAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X3 (WAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:10277",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X1 (WAN)" ],
       "text": "setAlias(Out X1 (WAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X1 (WAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:10298",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X2 (WAN)" ],
       "text": "setAlias(Out X2 (WAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X2 (WAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:10319",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X3 (WAN)" ],
       "text": "setAlias(Out X3 (WAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X3 (WAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VLAN Networks Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11351",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0:V2 (WIFI VISITANTES)" ],
       "text": "setAlias(In X0:V2 (WIFI VISITANTES))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0:V2 (WIFI VISITANTES)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11372",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0:V3 (CAMERAS CAIO)" ],
       "text": "setAlias(In X0:V3 (CAMERAS CAIO))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0:V3 (CAMERAS CAIO)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11393",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0:V6 (Estudo)" ],
       "text": "setAlias(In X0:V6 (Estudo))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0:V6 (Estudo)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11414",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0:V8 (VISITANTES_LAN)" ],
       "text": "setAlias(In X0:V8 (VISITANTES_LAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0:V8 (VISITANTES_LAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11435",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0:V62 (BEEHOME)" ],
       "text": "setAlias(In X0:V62 (BEEHOME))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0:V62 (BEEHOME)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11456",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0:V65 (WIFI SISTEMAS)" ],
       "text": "setAlias(In X0:V65 (WIFI SISTEMAS))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0:V65 (WIFI SISTEMAS)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11477",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "In X0:V70 (BLE)" ],
       "text": "setAlias(In X0:V70 (BLE))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Incoming Traffic on interface X0:V70 (BLE)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11498",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0:V2 (WIFI VISITANTES)" ],
       "text": "setAlias(Out X0:V2 (WIFI VISITANTES))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0:V2 (WIFI VISITANTES)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11519",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0:V3 (CAMERAS CAIO)" ],
       "text": "setAlias(Out X0:V3 (CAMERAS CAIO))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0:V3 (CAMERAS CAIO)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11540",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0:V6 (Estudo)" ],
       "text": "setAlias(Out X0:V6 (Estudo))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0:V6 (Estudo)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11561",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0:V8 (VISITANTES_LAN)" ],
       "text": "setAlias(Out X0:V8 (VISITANTES_LAN))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0:V8 (VISITANTES_LAN)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11582",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0:V62 (BEEHOME)" ],
       "text": "setAlias(Out X0:V62 (BEEHOME))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0:V62 (BEEHOME)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11603",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0:V65 (WIFI SISTEMAS)" ],
       "text": "setAlias(Out X0:V65 (WIFI SISTEMAS))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0:V65 (WIFI SISTEMAS)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:11624",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Out X0:V70 (BLE)" ],
       "text": "setAlias(Out X0:V70 (BLE))"
      }
     ],
     "group": { "filter": "Ativos de Rede" },
     "host": { "filter": "SonicWall - Cluster" },
     "item": {
      "filter": "Outgoing Traffic on interface X0:V70 (BLE)"
     },
     "options": {
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Audit - Caio Btu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit View",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "source": "url",
       "type": "json",
       "url": "https://172.16.1.150:4443/api/sonicos/log/audit/view",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "VPN - Loadbalance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:128",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Busscar" ],
         "text": "setAlias(Busscar)"
        }
       ],
       "group": { "filter": "VPNs/Links" },
       "host": { "filter": "VPNs - LOADBALANCE" },
       "item": { "filter": "ICMP ping - BUSSCAR" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:149",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Caio Barra" ],
         "text": "setAlias(Caio Barra)"
        }
       ],
       "group": { "filter": "VPNs/Links" },
       "host": { "filter": "VPNs - LOADBALANCE" },
       "item": { "filter": "ICMP ping - CAIO BARRA" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:170",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Caio CT" ],
         "text": "setAlias(Caio CT)"
        }
       ],
       "group": { "filter": "VPNs/Links" },
       "host": { "filter": "VPNs - LOADBALANCE" },
       "item": { "filter": "ICMP ping - CAIO CT" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:191",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Caio SP" ],
         "text": "setAlias(Caio SP)"
        }
       ],
       "group": { "filter": "VPNs/Links" },
       "host": { "filter": "VPNs - LOADBALANCE" },
       "item": { "filter": "ICMP ping - CAIO SP" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:212",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "CIGC" ],
         "text": "setAlias(CIGC)"
        }
       ],
       "group": { "filter": "VPNs/Links" },
       "host": { "filter": "VPNs - LOADBALANCE" },
       "item": { "filter": "ICMP ping - CIGC" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:233",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Inbrasp Matriz" ],
         "text": "setAlias(Inbrasp Matriz)"
        }
       ],
       "group": { "filter": "VPNs/Links" },
       "host": { "filter": "VPNs - LOADBALANCE" },
       "item": { "filter": "ICMP ping - INBRASP MATRIZ" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:254",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Inbrasp Betim" ],
         "text": "setAlias(Inbrasp Betim)"
        }
       ],
       "group": { "filter": "VPNs/Links" },
       "host": { "filter": "VPNs - LOADBALANCE" },
       "item": { "filter": "ICMP ping - BETIM" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "SSLVPN - Connected Users",
     "type": "stat",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "Sonicwall General" },
       "group": { "filter": "Ativos de Rede" },
       "host": { "filter": "SonicWall - Cluster" },
       "item": { "filter": "SSLVPN - Qtd. Users" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "SSLVPN - Connected Users",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "source": "url",
       "type": "json",
       "url": "https://172.16.1.150:4443/api/sonicos/reporting/ssl-vpn/sessions",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "SSLVPN - Connected Users",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Sonicwall General" },
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "" }
       ],
       "group": { "filter": "Ativos de Rede" },
       "host": { "filter": "SonicWall - Cluster" },
       "item": { "filter": "SSLVPN - Qtd. Users" },
       "method": "GET",
       "options": {
        "disableDataAlignment": true,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}